//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PilgrimageTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PilgrimageTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATGTTGGTGATACCCCCCGGACTGAGCGAGGAAGAGGAGGCTCTGCAGAAGAAATTCAACAAGCTCAAGAAAAAGAATGGAGACAGAGCGACTTG.
        /// </summary>
        internal static string GenBank_XMLParsing_MultipleCDSFeatureNodes_CDS {
            get {
                return ResourceManager.GetString("GenBank_XMLParsing_MultipleCDSFeatureNodes_CDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATGTCTATCCAGGTTGAGCATCCTGCTGGTGGTTACAAGAAACTGTTTGAAACTGTGGAGGAACTGTCCTCGCCGCTCACAGCTCATGTAACAGGCAGGATCCCCCTCTGGCTCACCGGCAGTCTCCTTCGATGTGGGCCAGGACTCTTTGAAGTTGGATCTGAGCCATTTTACCACCTGTTTGATGGGCAAGCCCTCCTGCACAAGTTTGACTTTAAAGAAGGACATGTCACATACCACAGAAGGTTCATCCGCACTGATGCTTACGTACGGGCAATGACTGAGAAAAGGATCGTCATAACAGAATTTGGCACCTGTGCTTTCCCAGATCCCTGCAAGAATATATTTTCCAGGTTTTTTTCTTACTTTCGAGGAGTAGAGGTTACTGACAATGCCCTTGTTAATGTCTACCCAGTGGGGGAAGATTACTACGCTTGCACAGAGACCAACTTTATTACAAAGATTAATCCAGAGACCTTGGAGACAATTAAGCAGGTTGATCTTTGCAACTA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenBank_XMLParsing_MultipleCDSRanges_CDS {
            get {
                return ResourceManager.GetString("GenBank_XMLParsing_MultipleCDSRanges_CDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCGTTCCTACAGGTAATGGGGCTGGCACGAGAGCAGCGCCGGGGACCGCCGTGAGGGCGCGCGGAAATCCAGCCCGTTATATAATGGAGCAGACACTGCCTGCGACCCCTGCTGCAGTTGGGGAATGGCGGTCAATGTGTATTCTACCTCGATAACCCAAGAGACTATGAGCAGACATGACATCATTGCATGGGTTAATGACATAGTATCTTTAAACTACACAAAAGTGGAACAGCTTTGTTCAGGAGCGGCCTATTGCCAATTCATGGACATGCTCTTCCCTGGCTGCATTAGTTTGAAGAAAGTAAAATTTCAAGCAAAGCTGGAACATGAATATATTCACAATTTTAAACTTCTGCAAGCATCATTTAAGCGAATGAACGTTGATAAGGTAATTCCAGTGGAGAAGCTAGTGAAAGGACGTTTCCAGGACAACCTGGATTTTATTCAATGGTTTAAGAAATTCTATGATGCTAACTACGATGGGAAGGAGTATGATCCTGTAGAGGCAC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenBank_XMLParsing_MultipleExonFeatureNodes_CDS {
            get {
                return ResourceManager.GetString("GenBank_XMLParsing_MultipleExonFeatureNodes_CDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATGCCTCTAAGAAAACACAGACAACACTTTAAAAAATATGGCAATTGTTTCACAGCGGGAGAAGCAGTGGATTGGCTTTATGGCCTGTTAAGAAGTAATAGCAATTTTGGTCCTGAAGTTACAAGGCAACAGACTATCCAGCTGTTGAGAAAGTTTCTTAAGAATCATGTCATTGAAGATATCAAAGGCAGATGGGGATCAGAACCTTGATGACAACAATCAGCTTTTCAGATTTCCTGCAACTTCTCCACTTAAAGCTCTTCCACGAAGGCATCCAGAATTGAGAAGAAATAGCACAGAGAACTTCTCTAAAGATAAAGATAGTGTTTTTAAATTACGAAACTTGTCTCGTAGAACTCCTAAAAAGCATGGATTGCATTTCTCTCAGGAAAATGCTGAGAAAATAAAGCATGAAATAATCAAAGATCAAGAAAAATCAATTGATAATAGAGAAATAAGCCAGGAAGATATTGAAGAAGTTTGGAGATATGTTATTCTGGTCTACCTGCAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenBank_XMLParsing_NoSequence_CDS {
            get {
                return ResourceManager.GetString("GenBank_XMLParsing_NoSequence_CDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATGGACGGGGCCGCGGGGCCCGGTGACGGCCCTGCTCGGGAGGCCCTCCAGTCTCTGAGCCAGCGGCTTCGGGTGCAGGAGCAGGAGATGGAACTGGTAAAGGCAGCCCTGGCAGAAGCCCTTCGCCTGCTGCGGCTGCAGGTGCCCCCTTCCTCCCTGCAGGGCTCTGGCACACCAGCTCCTCCGGGGGACAGTCTTGCAGCCCCCCCAGGACTGCCACCCACGTGCACCCCTTCCTTGGTGAGCCGAGGCACCCAGACGGAGACAGAGGTGGAGCTCAAGTCATCCCCTGGACCCCCTGGCCTGAGCAATGGACCCCCAGCCCCTCAGGGGGCCAGCGAAGAGCCTAGCGGGACCCAATCTGAAGGAGGGGGCAGCAGCAGCAGTGGTGCTGGCTCCCCTGGCCCCCCGGGGATCCTCAGGCCCTTGCAGCCCCCACAGCGTGCTGACACGCCGCGAAGAAATTCTTCCTCCTCCTCATCCCCCTCAGAGCGGCCTCGGCAGAAGCTCTC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenBank_XMLParsing_OverlappingCDSRanges_CDS {
            get {
                return ResourceManager.GetString("GenBank_XMLParsing_OverlappingCDSRanges_CDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATGCAGAGGGCGCGTGAGGCGCGCGACGAGCTCCCCGACGACTTCTACATCCCCATGGCGCTGGACGCGCCCAACCTGACGGCGCTGAGCCCGTTCCTGGTGCCGCAGACGCACCTGGGCAGCCCCGGCGTGTTCCGCGGCATGGCGGCGTTCATGCTGGCGCTGATCGCGCTGGGGGGGCCCATCAACGCGCTCACCATCGCCTGCACCGCGCGCTACAAGAAGCTGCGCTCGCACCTCAACTACATCCTGGTGAACCTGGCGGCCGCCAACCTGCTGGTGATCTGCGTGGGCTCCACCACCGCCTTCTACAGCTTCTCGCAGATGTACTTCGCGCTGGGGCCCACGGCGTGCAAGATCGAGGGCTTCGCCGCCACGCTCGGGGGCATGGTGTCGCTGTGGTCGCTGGCCGTGGTGGCCTTCGAGCGGTTCCTGGTGATCTGCAAGCCGCTGGGCAACTTCACGTTCCGCGGCAGCCACGCGGTGCTGGGCTGCGCCGCCACCTGGATCTT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenBank_XMLParsing_Segmented_CDS {
            get {
                return ResourceManager.GetString("GenBank_XMLParsing_Segmented_CDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATGTCCAGCCAAATTGAGCACCCAGCTGGTGGATACAAGAAGCTTTTTGAGACCGTGGAGGAATTGGCTGCACCAGTAACTGCTCATGTCACAGGCAGGATTCCCATATGGCTTACAGGCAGTCTGCTTAGATGTGGGCCTGGCTTATTTGAAGTTGGTTCGGAACCATTTTATCATTTGTTTGATGGCCAAGCGCTTCTTCATAAATTTGACTTTAAGGAGGGACATGTCACATACCATCGCAGATTCATTCGGACTGATGCTTATGTAAGAGCAATGACTGAGAAAAGAATCGTGATAACTGAATTTGGCACCTGTGCTTACCCTGATCCATGCAAGAACATATTTTCCAGGTTTTTTTCATACTTCAAAGGTGTGGAGGTCACTGATAATGCCCTGGTTAATGTGTACCCAGTGGGTGAAGATTACTATGCCTGCACAGAGACCAACTTTATCACCAAGATTAACCCAGAGACTTTGGAGACAATCAAGCAGGTGGACCTTTGTAAATA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenBank_XMLParsing_SingleCDSRange_CDS {
            get {
                return ResourceManager.GetString("GenBank_XMLParsing_SingleCDSRange_CDS", resourceCulture);
            }
        }
    }
}
